FROM debian:jessie
MAINTAINER Naoaki Obiki

RUN apt-get update

#include "./include/useradd.docker"
#include "./include/plain.docker"

#include "./include/xvfb.docker"
#include "./include/browser.docker"
#include "./include/selenium-behat.docker"

#include "./include/php.docker"

#include "./include/apache2.docker"

#include "./include/mariadb-client.docker"
